version: '3.9'

services:
  database:
    container_name: url_shortener_mongo
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
      MONGO_INITDB_DATABASE: url_shortener
    ports:
      - '27017:27017'
    volumes:
      - url-shortener-mongo-data:/data/db

volumes:
  url-shortener-mongo-data:
