version: '3.9'

services:
  database:
    container_name: mongodb
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
